# Generated by Django 3.2 on 2021-04-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_active_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
