# Generated by Django 3.2 on 2021-04-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_auto_20210423_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endurance',
            name='endurance',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='stat',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='total',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='strength',
            name='strength',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=10),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='wisdom',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
