# Generated by Django 3.2 on 2021-04-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_auto_20210423_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='active_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='quests.user', null=True, blank=True),
        ),
    ]
