# Generated by Django 3.2 on 2021-04-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_alter_quest_active_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='first name', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last name', max_length=50),
        ),
    ]
